# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fresco' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fresco

  pod 'SnapKit', '~> 5.0.0'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'RxGesture', '~> 4.0'
  pod 'RxDataSources', '~> 5.0'

  target 'FrescoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '6.5.0'
    pod 'RxTest', '6.5.0'
  end

  target 'FrescoUITests' do
    # Pods for testing
  end

end
